[maxytec-hi3798mv] Set PREFERRED_PROVIDER_virtual/libgbm to mesa
For now?

Fix:

ERROR: Nothing PROVIDES 'mesa' (but /home/hains/wrynose/openpli-oe-core/meta-maxytec/
recipes-bsp/mali/maxytec-mali-multibox.bb DEPENDS on or otherwise requires it)
mesa was skipped: PREFERRED_PROVIDER_virtual/libgbm set to maxytec-mali-multibox, not mesa