[linux-firmware-local] Fix license-checksum
Fix:

ERROR: firmware-zd1211-1.1+git-r0 do_populate_lic: QA Issue: firmware-zd1211: Recipe file fetches
files and does not have license file information (LIC_FILES_CHKSUM) [license-checksum]