[python3-twisted] Add python3-pickle to RDEPENDS
Removed from RDEPENDS python3-cheetah with commit:
https://github.com/Hains/openpli-oe-core/commit/147111480511a51bd5b1cdae7f3b9589af142275

Add it to RDEPENDS python3-twisted, where it belongs.

Fix:

  File "/usr/lib/python3.14/site-packages/twisted/internet/interfaces.py", line 16, in <module>
    from twisted.python.failure import Failure
  File "/usr/lib/python3.14/site-packages/twisted/python/failure.py", line 29, in <module>
    from twisted.python import reflect
  File "/usr/lib/python3.14/site-packages/twisted/python/reflect.py", line 13, in <module>
    import pickle
ModuleNotFoundError: No module named 'pickle'