[mountmanger] don't unmount device when root is none(WIP)
Unmount device when root is none leads to a read-only image, with errors like

plugin.py", line 782, in add_fstab
OSError: [Errno 30] Read-only file system: '/etc/fstab.tmp'

Also fix crash when device name is '/dev/sdb' for example.
self.device_uuid will not become defined and leads to error:

File "/usr/lib/enigma2/python/Plugins/SystemPlugins/MountManager/plugin.py", line 786, in add_fstab
    open('/etc/fstab.tmp', 'w').writelines([l for l in open('/etc/fstab').readlines() if self.device_uuid not in l])
                                                                                         ^^^^^^^^^^^^^^^^
AttributeError: 'DevicesMountPanel' object has no attribute 'device_uuid'. Did you mean: 'device_tmp'?