[wget] Fix build against OpenSSL 4.0
SSLv3_client_method() method has been removed.

Fix:

| ../../sources/wget-1.25.0/src/openssl.c:230:14: error: implicit declaration of function
'SSLv3_client_method'; did you mean 'SSLv23_client_method'? [-Wimplicit-function-declaration]
|   230 |       meth = SSLv3_client_method ();
|       |              ^~~~~~~~~~~~~~~~~~~
|       |              SSLv23_client_method