djmount: Fix build with std-c++23
-Get rid of PROTO_LIST macro.
-Fix incompatible pointer type.
-Fix linker error due to non-static inline function.

| ../../../sources/djmount-0.71/libupnp/upnp/src/uuid/md5.c:122:1: error: number of arguments doesn't match prototype
|   122 | {
|       | ^
| In file included from ../../../sources/djmount-0.71/libupnp/upnp/src/uuid/md5.c:30:
| ../../../sources/djmount-0.71/libupnp/upnp/src/inc/md5.h:36:6: error: prototype declaration
|    36 | void MD5Init PROTO_LIST ((MD5_CTX *));
|       |      ^~~~~~~

 ../../../sources/djmount-0.71/libupnp/upnp/src/uuid/sysdep.c: In function 'get_random_info':
| ../../../sources/djmount-0.71/libupnp/upnp/src/uuid/sysdep.c:157:20: error: passing argument 2 of 'MD5Update'
 from incompatible pointer type [-Wincompatible-pointer-types]
|   157 |     MD5Update( &c, &r, sizeof( randomness ) );
|       |                    ^~

cortexa15hf-neon-vfpv4-oe-linux-gnueabi/djmount/0.71/build/libupnp/upnp/.libs/libupnp.a(libupnp_la-webserver.o): in function `get_file_info':
| /usr/src/debug/djmount/0.71/libupnp/upnp/src/genlib/net/http/webserver.c:628:(.text+0x148): undefined reference to `get_content_type'
| collect2: error: ld returned 1 exit status